### PR TITLE
Bundle i2p libs, set bootstrap on startup

### PR DESCRIPTION
**Pull request by majestrate**
also, removed the exe file from the git repo, that can be added in releases on github
also, moved bootstrap to my stable server at psi.i2p.

feel free to merge as desired.

### CODE REVIEW

**Comment by metamarcdw** [comment]
Check https://github.com/Bitmessage/PyBitmessage/blob/master/src/helper_startup.py
Lines # 89-90

```
        shared.config.set(
            'bitmessagesettings', 'messagesencrypted', 'false')
```

FWIW, I can't actually find this config setting actually being used anywhere in the code.

**Comment by metamarcdw** [comment]
If you are going serve bootstrap.json from psi.i2p, how would you prefer to keep the list updated? If you give me a BM+ address I can put it in the readme or forward to it.

**Comment by majestrate** [comment]
I am thinking that there should be a git repo for an "official" website that contains the bootstrap.json (perhaps a webapp that generates one from previous bootstrap requests) , docs, etc. that way it's managed in the open. 
many i2p applications already use a bootstrap infrastructure called "seedless", a trustless http based dht inside i2p. it may be a good idea to utilize that instead of 1 static bootstrap server.

**Comment by metamarcdw** [comment]
I very much agree with that, especially using Seedless. But for the time being can I forward to a BM+ or a @mail.i2p?

**Comment by metamarcdw** [comment]
I definitely agree with that, esp. using Seedless. Is there any documentation regarding Seedless other than what is found at sponge.i2p? I find those docs to be more confusing than helpful TBH.

**Comment by metamarcdw** [comment]
This is what we've got thus far.
https://github.com/metamarcdw/I2PBMweb

**Comment by metamarcdw** [comment]
Added a new node to bootstrap.json in the above repo. Please update your copy at your convenience.

**Pull request merged**
