### PR TITLE
I2P Setup for PyBitmessage-I2P

### PR DESCRIPTION
**Pull request by koeur2pi**

### CODE REVIEW

**Comment by metamarcdw** [comment]
The plugins are not "required" for 0.2.0 to function.

**Comment by koeur2pi** [comment]
Then FYI there are errors in:
- http://i2pwiki.i2p/index.php?title=PyBitmessage-I2P#I2P_Setup_.28to_do_.21.29
- http://i2pwiki.i2p/index.php?title=Seedless#Examples_of_softwares_that_use_Seedless

You should write here (wiki ?) if Seedless is optional or not, and if installing it (Seedless+Neodatis) is useful for v0.2.0 or not.

**Comment by metamarcdw** [comment]
Thanks. I was not aware that these pages even existed.

**Comment by metamarcdw** [comment]
We do rely totally on the existence of Seedless servers in the network, but not on the existence of the Seedless plugin on the local machine.

**Pull request closed without merging**
